# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9e011d893f56f779586bf6371426be3ea989a99f69d5dfdf21357c955c1c0209e696d95cc01c52b0c1fd7dc74eaca2965d25045775c7206607f3bd8772d07c

test:
  secret_key_base: 9b8b488bbd03ed601954856709c3a036dcfaf2ad9ca1a91eb3cdbd17405e75054defd02cb17c2c977a9da378ee3cfe52613c82bed42227ed7bdaa5ac2d9f2df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
